# Generated by Django 5.2.1 on 2025-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='followed_strategy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='strategy_outcome',
            field=models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Loss')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
