# Generated by Django 5.2.1 on 2025-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_trade_followed_strategy_trade_strategy_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(),
        ),
    ]
