# Generated by Django 5.2.1 on 2025-07-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_trade_strategy_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_images/'),
        ),
    ]
