# Generated by Django 5.2.1 on 2025-07-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_journalentry_chart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='auto_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
